#是否允许私聊使用
allowPM: true
#是否排除 AI 作品
excludeAI: false
#获取张数大于前面的数时则使用对应的图片大小 可选值: ['mini', 'thumb', 'small', 'regular', 'original']
imgSize:
  6: "regular"
  # 9: 'small'
  # 15: 'thumb'
#每名用户每日次数限制（0 则无限制）
limit: 30

#每个群和私聊的默认设置，单独设置后则失效，时间单位: 秒(s)
defSet:
  r18: 0 #1开启0关闭
  recall: 120 #撤回时间
  cd: 300

# 私聊设置
friendSet:
  # 私聊只支持全局r18设置 #1开启0关闭
  r18: 0
  # 设置好友cd qq: cd(秒)
  123456: 200
  456789: 300

# 群单独设置
12346:
  r18: 1

456789:
  cd: 60
